library("reshape2")
library('ggplot2')
library(ggthemes)
dats = read.csv('/Users/mb/Desktop/Janis.so/06_qmul/BeatBopper/users/analysis/DRIFT/drift_t.csv')
end = length(dats)
frequency <- 1/mean(dats$time[2:end]-dats$time[1:(end-1)])
library("allanvar")
avar.data.x <- avar(dats$phase,frequency)
plot(avar.data.x$time,avar.data.x$av,type="l",col="green")
